modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="cyberhive"
version="0.1.0"
displayName="Cyber Hive"
authors="Somdudewillson"

[[dependencies.cyberhive]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"




